---
shortcuts:
  hostname: tandoor.company
workload:
  kind: Deployment
  strategy:
    type: RollingUpdate
  containers:
    navidrome:
      image:
        registry: registry.hub.docker.com
        repository: vabene1111/recipes
        tag:
        pullPolicy: Always
      ports:
        tandoor: tandoor
      envFrom:
        - main
      mounts:
        storage:
          staticfiles:
            path: /opt/recipes/staticfiles
          mediafiles: 
            path: /opt/recipes/mediafiles
      livenessProbe:
        httpGet:
          path: /
          port: 8080
        initialDelaySeconds: 3
        periodSeconds: 3
      readinessProbe:
        httpGet:
          path: /
          port: 8080
        initialDelaySeconds: 3
        periodSeconds: 3
ingress:
  main:
    enabled: true
    annotations: {}
    class: traefik
    rules:
      - host: '{{ .Values.shortcuts.hostname }}'
        http:
          paths:
            - backend:
                service:
                  name: '{{ include "chart.fullname" $ }}-navidrome'
                  port:
                    number: 8080
              path: /
              pathType: Prefix
    tls:
      - hosts:
          - '{{ .Values.shortcuts.hostname }}'
        secretName: '{{ .Values.shortcuts.hostname }}'

service:
  tandoor:
    enabled: true
    type: ClusterIP
    ports:
      tandoor:
        port: 8080
        targetPort: 8080
        protocol: TCP
storage:
  staticfiles:
    enabled: true
    storageClassName: default
    size: 512Mi
    accessModes:
      - ReadWriteOnce
  mediafiles:
    enabled: true
    storageClassName: default
    size: 1Gi
    accessModes:
      - ReadWriteOnce


env:
  main:
    enabled: true
    sensitive: false
    remove: []
    data: {}
  secrets:
    enabled: true
    sensitive: true
    remove: []
    data:
      SECRET_KEY: "..."

