---
shortcuts:
  backendURL: kitchenowl-api.company
  frontendURL: kitchenowl.company
  backendProto: https
  frontendProto: https

base:
  workload:
    kind: Deployment
    strategy:
      type: RollingUpdate
    containers:
      kitchenowl-web:
        image:
          registry: registry.hub.docker.com
          repository: tombursch/kitchenowl
          tag:
          pullPolicy: Always
        ports:
          frontend: 
            - http
        volumeMounts:
          storage:
            data:
          extraVolumes:
            nginx-cache:
              path: /var/cache/nginx/
            run:
              path: /run
        envFrom:
          backend-env: {}
          backend-secrets: {}
          frontend-env: {}
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
ingress:
  frontend:
    enabled: true
    annotations: {}
    class: traefik
    rules:
      - host: '{{ .Values.shortcuts.frontendURL }}'
        http:
          paths:
            - backend:
                service:
                  name: '{{ $.Release.Name }}-frontend'
                  port:
                    number: 8080
              path: /
              pathType: Prefix
    tls:
      - hosts:
          - '{{ .Values.shortcuts.frontendURL }}'
        secretName: '{{ .Values.shortcuts.frontendURL }}'

extraVolumes:
  # -- Because by default the fs is read-only, we need to add an emtpy dir volume
  nginx-cache:
    emptyDir: {}
  run:
    emptyDir: {}

services:
  frontend:
    enabled: true
    type: ClusterIP
    ports:
      http:
        port: 8080
        targetPort: 8080
        protocol: TCP

storage:
  data:
    enabled: true
    storageClassName: default
    size: 1Gi
    accessModes:
      - ReadWriteOnce

config:
  env:
    frontend-env:
      enabled: true
      sensitive: false
      remove: []
      data:
        BACK_URL: '{{ .Values.shortcuts.backendProto }}://{{ .Values.shortcuts.backendURL }}'
  
    backend-env:
      enabled: true
      sensitive: false
      remove: []
      data:
        STORAGE_PATH: /app/data
        FRONT_URL: '{{ .Values.shortcuts.frontendProto }}://{{ .Values.shortcuts.frontendURL }}'
    
    backend-secrets:
      enabled: true
      sensitive: true
      remove: []
      data: {}
  
