image:
  registry: docker.io
  repository: stalwartlabs/stalwart
  tag:
  pullPolicy: Always

config:
  bootstrap: true
  datastore: {}
  recoveryAdmin:
    username: admin
    password: qwertyu9

extra:
  database:
    enabled: true
    instance:
      name: cloudnative-pg17
      # -- Either mysql or postgres
      type: ~
    deletionProtected: true
    useTLS: false
