image:
  registry: docker.io
  repository: stalwartlabs/stalwart
  tag:
  pullPolicy: Always

config:
  datastore: {}
  recoveryAdmin:
    username: admin
    password: qwertyu9

extra:
  database:
    enabled: true
    instance:
      name: ~
      # -- Either mysql or postgres
      type: ~
    deletionProtected: true
    useTLS: false
