apiVersion: v1
kind: Service
metadata:
  name: {{ include "openvpn-chart.fullname" . }}
  labels:
    {{- include "openvpn-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      {{- if .Values.service.nodePort }}
      nodePort: {{ int .Values.service.nodePort }}
      {{- end}}
      targetPort: {{ .Values.service.port | default 1194 }}
      protocol: {{ .Values.service.protocol | default "UDP" | quote }}
      name: openvpn
  selector:
    {{- include "openvpn-chart.selectorLabels" . | nindent 4 }}
