---
{{- if $.Capabilities.APIVersions.Has "traefik.io/v1alpha1/IngressRouteTCP" -}}
{{- if .Values.tcproute.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ include "openvpn-chart.fullname" . }}
  labels:
    {{- include "openvpn-chart.labels" . | nindent 4 }}
spec:
{{ tpl (.Values.tcproute.spec | toYaml | indent 2 | toString) $  }}
{{- end }}
{{- end }}
