apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.name" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      {{- include "common.selectorLabels" . | nindent 4 }}
  template:
    metadata:
      labels:
        {{- include "common.labels" . | nindent 4 }}
    spec:
      initContainers:
        - name: stalwart-bootstrap
          env: 
            - name: STALWART_RECOVERY_MODE
              value: "true"
            - name: STALWART_RECOVERY_ADMIN
              valueFrom:
                secretKeyRef:
                  key: STALWART_RECOVERY_ADMIN
                  name: {{ include "common.name" . }}-admin-credentials
          volumeMounts:
            - name: datastore
              mountPath: /opt/stalwart/config.yaml
              subPath: config.yaml
              readOnly: true
          imagePullPolicy: '{{ .Values.image.pullPolicy }}'
          image: {{ include "image.bootstrap" (dict "ctx" . "image" .Values.image) }}
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              memory: 128Mi
      containers:
        - name: stalwart
          command:
          - /usr/sbinx/configure_gitea.sh
          imagePullPolicy: '{{ .Values.image.pullPolicy }}'
          image: {{ include "image.bootstrap" (dict "ctx" . "image" .Values.image) }}
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
          securityContext:
            runAsUser: 1000
          volumeMounts:
            - name: datastore
              mountPath: /opt/stalwart/config.yaml
              subPath: config.yaml
              readOnly: true
      restartPolicy: Always
      securityContext:
        fsGroup: 1000
      terminationGracePeriodSeconds: 60
      volumes:
      - name: datastore
        secret:
          defaultMode: 420
          secretName: {{ include "common.name" . }}-datastore
