apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.name" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      {{- include "common.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "common.labels" . | nindent 8 }}
    spec:
      {{- if .Values.config.bootstrap }}
      initContainers:
        - name: stalwart-bootstrap
          imagePullPolicy: '{{ .Values.image.pullPolicy }}'
          image: ubuntu
          command:
            - bash
          args:
            - -c
            - "apt-get update && apt-get install -y curl xz-utils && curl --proto '=https' --tlsv1.2 -LsSf https://github.com/stalwartlabs/cli/releases/latest/download/stalwart-cli-installer.sh | sh"
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      {{- end }}
      containers:
        - name: stalwart
          args:
          - --config 
          - /opt/stalwart/config.yaml
          imagePullPolicy: '{{ .Values.image.pullPolicy }}'
          image: {{ include "image.bootstrap" (dict "ctx" . "image" .Values.image) }}
          {{- if .Values.config.bootstrap }}
          env: 
            - name: STALWART_RECOVERY_MODE
              value: "true"
            - name: STALWART_RECOVERY_ADMIN
              valueFrom:
                secretKeyRef:
                  key: recovery_admin
                  name: {{ include "common.name" . }}-admin-credentials
          {{- end }}
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
          securityContext:
            runAsUser: 1000
          volumeMounts:
            - name: datastore
              mountPath: /opt/stalwart/config.yaml
              subPath: config.yaml
              readOnly: true
      restartPolicy: Always
      securityContext:
        fsGroup: 1000
      terminationGracePeriodSeconds: 60
      volumes:
      - name: datastore
        secret:
          defaultMode: 420
          secretName: {{ include "common.name" . }}-datastore
      - name: tmp
        emptyDir: {}
