apiVersion: v2
name: team-fortress-2
description: A Helm chart for running a Team Fortress 2 server
type: application
version: 0.2.0
appVersion: "latest"
maintainers:
  - name: allanger
    email: allanger@badhouseplants.net
    url: https://badhouseplants.net
dependencies:
  - name: helm-library
    version: 0.2.5
    repository: oci://ghcr.io/allanger/allangers-helm-library
annotations:
  allowed_workload_kinds: "Deployment"
  # -- Skipping tests because it requires a very big volume
  skip_tests: "true"

