{{- define "lib.core.configmap" -}} {{- /* define[0] */}}
{{- include "lib.error.noCtx" . -}}
{{- include "lib.error.noKey" (dict "ctx" . "key" "metadata") -}}
---
# ---------------------------------------------------------------------
# -- This resource is managed by the allanger's helm library
# ---------------------------------------------------------------------
apiVersion: v1
kind: ConfigMap
metadata: 
{{ .metadata | indent 2 }}
data:
{{- range $key, $value := .data }}
  {{- if $value }}
  {{ $key }}: {{ tpl $value $.Context | quote }}
  {{- end }}
{{- end }}
{{- end -}} {{- /* /define[0]) */ -}}
