---
shortcuts:
  hostname: memos.company

base:
  workload:
    kind: Deployment
    strategy:
      type: RollingUpdate
    containers:
      memos:
        image:
          registry: registry.hub.docker.com
          repository: neosmemo/memos
          tag:
          pullPolicy: Always
        ports:
          main:
            - memos
        envFrom:
          main: {}
        volumeMounts:
          storage:
            data:
              path: /var/opt/memos
        livenessProbe:
          httpGet:
            path: /
            port: 5230
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /
            port: 5230 
          initialDelaySeconds: 3
          periodSeconds: 3

ingress:
  main:
    enabled: true
    annotations: {}
    class: traefik
    rules:
      - host: '{{ .Values.shortcuts.hostname }}'
        http:
          paths:
            - backend:
                service:
                  name: '{{ include "chart.fullname" $ }}-main'
                  port:
                    number: 5230
              path: /
              pathType: Prefix
    tls:
      - hosts:
          - '{{ .Values.shortcuts.hostname }}'
        secretName: '{{ .Values.shortcuts.hostname }}'

services:
  main:
    enabled: true
    type: ClusterIP
    ports:
      memos:
        port: 5230
        targetPort: 5230
        protocol: TCP
storage:
  data:
    enabled: true
    storageClassName: default
    size: 1Gi
    accessModes:
      - ReadWriteOnce

config:
  env:
    main:
      enabled: true
      sensitive: false
      remove: []
      # -- For example: https://www.usememos.com/docs/install/database
      data: []
