---
shortcuts:
  backendURL: kitchenowl-api.company
  frontendURL: kitchenowl.company
  backendProto: https
  frontendProto: https

base:
  workload:
    kind: Deployment
    strategy:
      type: RollingUpdate
    containers:
      kitchenowl:
        image:
          registry: registry.hub.docker.com
          repository: tombursch/kitchenowl-backend
          tag:
          pullPolicy: Always
        ports:
          backend: 
            - http
        envFrom:
          backend-env: {}
          backend-secrets: {}
        volumeMounts:
          storage:
            data:
              path: /app/data
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 3
          periodSeconds: 3
        startupProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 3
          periodSeconds: 3
          failureThreshold: 80
ingress:
  backend:
    enabled: true
    annotations: {}
    class: traefik
    rules:
      - host: '{{ .Values.shortcuts.backendURL }}'
        http:
          paths:
            - backend:
                service:
                  name: '{{ $.Release.Name}}-backend'
                  port:
                    number: 5000
              path: /
              pathType: Prefix
    tls:
      - hosts:
          - '{{ .Values.shortcuts.backendURL }}'
        secretName: '{{ .Values.shortcuts.backendURL }}'

services:
  backend:
    enabled: true
    type: ClusterIP
    ports:
      http:
        port: 5000
        targetPort: 5000
        protocol: TCP

storage:
  data:
    enabled: true
    storageClassName: default
    size: 1Gi
    accessModes:
      - ReadWriteOnce

config:
  env:
    backend-env:
      enabled: true
      sensitive: false
      remove: []
      data:
        STORAGE_PATH: /app/data
        FRONT_URL: '{{ .Values.shortcuts.frontendProto }}://{{ .Values.shortcuts.frontendURL }}'
    backend-secrets:
      enabled: true
      sensitive: true
      remove: []
      data: {}
  
